apiVersion: apps/v1
kind: Deployment
metadata:
  name: websoftphone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-websoftphone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-websoftphone
    spec:
      containers:
      - image: docker-registry.ringplan.com/dev/ringplan_voice_pwa:latest
        name: websoftphone
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webphone-service
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: app-websoftphone
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webphone-ingress
spec:
  rules:
  - host: "webphone.dev.k8s"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: webphone-service
          servicePort: 80
